#index:
#    path: /
#    controller: App\Controller\DefaultController::index
index:
    path: /
    controller: App\Controller\AccueilController::index

voyages:
    path: /voyages
    controller: App\Controller\VoyagesController::voyages